version: '3.9'

services:
  projectsend:
    container_name: projectsend
    image: lscr.io/linuxserver/projectsend:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuching
      - MAX_UPLOAD=50000
    volumes:
      - /data/projectsend/config:/config
      - /data/projectsend/data:/data
    ports:
      - 81:80
    restart: unless-stopped